apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: insights-ocp-scanner
    name: insights-ocp-scanner
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: docker.io/rexwhite/insights-ocp-scanner
#      importPolicy:
#        scheduled: true
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: insights-ocp-controller
    name: insights-ocp-controller
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: docker.io/rexwhite/insights-ocp-controller
#      importPolicy:
#        scheduled: true
      name: latest
      referencePolicy:
        type: Source

- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    name: insights-scanner
  spec:
    selector:
      matchLabels:
        name: insights-scanner
#    updateStrategy:
#      type: RollingUpdate
    template:
      metadata:
        name: insights-scanner
        labels:
          name: insights-scanner
      spec:
#        tolerations:
#        - key: node-role.kubernetes.io/master
#          effect: NoSchedule
        containers:
        - name: insights-ocp-controller
          image: docker-registry.default.svc:5000/baal/hola:latest
          env:
          - name: SCANNER_IMAGE
            value: docker-registry.default.svc:5000/insights-scan/insights-ocp-scanner
          - name: SCAN_API
            valueFrom:
              secretKeyRef:
                name: insights-controller-credentials
                key: scanapi
          - name: INSIGHTS_USERNAME
            valueFrom:
              secretKeyRef:
                name: insights-controller-credentials
                key: username
          - name: INSIGHTS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: insights-controller-credentials
                key: password
          - name: INSIGHTS_PROXY
            valueFrom:
              secretKeyRef:
                name: insights-controller-credentials
                key: proxy
          - name: INSIGHTS_AUTHMETHOD
            value: BASIC
          command:
            - /insights-controller
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 500m
          volumeMounts:
            -
              name: dockersocket
              mountPath: /var/run/docker.sock
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
          securityContext:
            privileged: true
        initContainers:
        - name: insights-ocp-scanner-init
          image: docker.io/rexwhite/insights-ocp-scanner:latest
          command: ['sh', '-c', 'true']
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: insights-scan
      serviceAccount: insights-scan
      securityContext:

kind: List
metadata: {}
